### ISSUE TITLE
Mobile screen format

### ISSUE THREAD

**Issue by hkeshani** [hkeshani/shahnama-storyscroll#4]
The mobile screen display overlays the text over the image rendering the image unviewable. Interface needs to be redesigned, perhaps pullout text or split screen?

**Comment by jonchou3** [comment]
clickable hide/show button should still allow scrolling while element is hidden (or figure out a workaround)

**Comment by hkeshani** [comment]
Used solution from https://github.com/hkeshani/possesso

style.css is for mobile format
style-desktop.css is for desktop format
